### PR TITLE
Avoid iterating too much on items

### PR DESCRIPTION
**Pull request by VladimirSvoboda**
This patch fixes an issue causing too much iterations on the unit items.

The units were iterated over twice, in: `tasks/main.yml` and in
`tasks/common/config.yml`.
Keep only the second loop.

### CODE REVIEW

**Review by rook59 — APPROVED** [review]
:+1:
The CI does not fail due to this change but because of linting issues in other files

**Comment by rook59** [comment]
@0x0I can we get this merged?

**Comment by 0x0I** [comment]
> 👍
> The CI does not fail due to this change but because of linting issues in other 

> @0x0I can we get this merged?

For sure - was planning on tackling this lint issue and similar instances in other roles in batch when I got some time.

Will merge this for now though and thanks for the fix!

**Comment by VladimirSvoboda** [comment]
@0x0I Thanks for the merge! When do you plan to release a new version?

**Pull request merged**
